name: test-runner-integration-33320

on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message'
        required: false
        default: 'Integration test from self-hosted runner'

jobs:
  test-self-hosted-runner:
    runs-on: self-hosted

    steps:
    - name: Test runner info
      run: |
        echo "🤖 Integration test running on self-hosted runner"
        echo "Runner name: $RUNNER_NAME"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "Workflow: $GITHUB_WORKFLOW"
        echo "Test message: ${{ github.event.inputs.test_message || 'Integration test from self-hosted runner' }}"

    - name: Test basic commands
      run: |
        echo "Testing basic commands..."
        whoami
        pwd
        uname -a
        docker --version || echo "Docker not available"

    - name: Test success marker
      run: |
        echo "INTEGRATION_TEST_SUCCESS=true" >> $GITHUB_ENV
        echo "✅ Integration test completed successfully!"
